version: '3.4'

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    container_name: db
    volumes:
      - ./rethinkdb/rethinkdb_data:/data
    ports:
      - 8081:8080
      - 28015:28015
      - 29015:29015
    command: rethinkdb --bind all -d /data
    networks:
      - net
  api:
    image: golang:1.17.1
    container_name: api
    volumes:
      - ./api/realtimeweb:/api/realtimeweb
    ports:
      - 8765:8765
    environment:
      DB_HOST: "${DB_HOST}"
    depends_on:
      - rethinkdb
    working_dir: /api
    # FIXME: Ensure to start after the db container has started
    command: /bin/sh -c "sleep 2 && ./realtimeweb"
    networks:
      - net
  nginx:
    image: nginx:1.21.3
    container_name: frontend
    volumes:
      - ./frontend/etc/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./frontend/public:/var/www
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - ROOT=/var/www/
    # FIXME: Ensure to start after the api container has started
    command: /bin/sh -c "sleep 4 && envsubst '$$ROOT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - net
networks:
  net:
    driver: bridge
